# Generated by Django 3.1.7 on 2021-05-12 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_remove_profile_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mobile',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
