# Generated by Django 3.1.7 on 2021-06-05 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20210603_1922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='ProductId',
        ),
    ]
