# Generated by Django 3.1.7 on 2021-06-06 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_remove_product_productid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductName', models.CharField(max_length=50)),
                ('ProductPrice', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ProductQty', models.IntegerField()),
                ('ProductTotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('UserName', models.CharField(max_length=30)),
                ('ProductImage', models.FileField(upload_to='prod_uploads/')),
            ],
        ),
    ]
