# Generated by Django 3.1.7 on 2021-06-07 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrderDate', models.DateField(auto_now=True)),
                ('UserName', models.CharField(max_length=30)),
                ('OrderTotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('Status', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='OrdersItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrderId', models.IntegerField()),
                ('ProductID', models.IntegerField()),
                ('ProductName', models.CharField(max_length=50)),
                ('ProductPrice', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ProductQty', models.IntegerField()),
                ('ProductTotal', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
    ]
