# Generated by Django 3.1.7 on 2021-06-11 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_orders_ordersitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='ProductID',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
